### PR TITLE
SpotifyNoControl with automatic appId matching

### PR DESCRIPTION
**Pull request by JulienMaille**

### CODE REVIEW

**Comment by bernawastaken** [comment]
Not sure what the issue could be in here but it simply does not open Spotify. Running in cmd gives me this issue though 
image
Could it be some sort of incompatibility with the AppID?

**Comment by JulienMaille** [comment]
have you pinned SpotifyNoControl.exe to the taskbar?
I will share sourcecode so you can contribute

**Comment by bernawastaken** [comment]
Pinning to the taskbar opens up spotify and outputs some info to the cmd, though it shows two different taskbar apps
image
image
It also doesnt seem to work as intended but I am also having issues with the default SpotifyNoControl so that might be unrelated 
image

**Comment by JulienMaille** [comment]
I think you should not pin Spotify, just pin SpotifyNoControl
Maybe it won't work on first attempt, try twice

**Comment by bernawastaken** [comment]
Spotify is not pinned in this situation, only SpotifyNoControl is. I also tried multiple times with both the latest commit and the initial commit you mad and it doesn't work, though it should be noted the original version is not working as well. I'll try to get someone who has SpotifyNoControl working to test this out and I'll post the results here once I have them

**Comment by JulienMaille** [comment]
So it works out of the box for your friend?
In your case, what paths are printed out in the cmd? Do they match your shortcuts locations?

**Comment by bernawastaken** [comment]
Yes it worked out of the box for them. Also as I was opening the shortcut again it seems to be working, though I wouldn't put my money on it remaining consistent, as it happened before with the default version (probably it's either an issue with the default version or windows just acting up). Anyway, it's working great now for both my friend and I so I am fairly confident in saying it might be ready for the masses. Thought it might be a good idea to also include the exe in the non dynamic Dribbblish folder as it also uses SpotifyNoControl. Anyway, great job on this and I guess @morpheusthewhite might want to have a look at this now.

**Comment by morpheusthewhite** [comment]
Great job @JulienMaille

**Comment by JulienMaille** [comment]
@morpheusthewhite This tool has nothing to do in a specific folder theme, does it?
Should I move the exe up in the root folder? and commit the .cpp file

**Comment by morpheusthewhite** [comment]
I think it is not really needed, you can just update the binaries on both Dribbblish themes since we probably won't need to change these files again

**Comment by JulienMaille** [comment]
@bernawastaken do you want the source code so you can improve it?

```c++
#include <Windows.h>
#include <shobjidl_core.h>
#include <stdio.h>
#include <string>
#include <iostream>

using namespace std;

EXTERN_C const PROPERTYKEY DECLSPEC_SELECTANY PKEY_AppUserModel_ID =
{ { 0x9F4C2855, 0x9F79, 0x4B39,
{ 0xA8, 0xD0, 0xE1, 0xD4, 0x2D, 0xE1, 0xD5, 0xF3, } }, 5 };

void LaunchSpotify(LPWSTR launcher) {
    STARTUPINFO si;
    PROCESS_INFORMATION pi;

    ZeroMemory(&si, sizeof(si));
    si.cb = sizeof(si);
    ZeroMemory(&pi, sizeof(pi));

    CreateProcess(NULL,
        launcher,
        NULL,
        NULL,
        FALSE,
        CREATE_NO_WINDOW,
        NULL,
        NULL,
        &si,
        &pi
    );

    WaitForSingleObject(pi.hProcess, 5000);

    CloseHandle(pi.hProcess);
    CloseHandle(pi.hThread);
}

void doOrDie(HRESULT hr, string message) {
    if( !SUCCEEDED(hr) ) {
        wcout << "Error: " << message.c_str() << endl;
        exit(1);
    }
}

bool setAppId(LPWSTR path, LPWSTR name)
{
    doOrDie(CoInitializeEx(NULL, COINIT_APARTMENTTHREADED), "Failed to initialize COM");

    IShellLink* link;
    doOrDie(CoCreateInstance(CLSID_ShellLink, NULL, CLSCTX_INPROC_SERVER, IID_PPV_ARGS(&link)), "Failed to create ShellLink object");

    IPersistFile* file;
    doOrDie(link->QueryInterface(IID_PPV_ARGS(&file)), "Failed to obtain PersistFile interface");
    doOrDie(file->Load(path, STGM_READWRITE), "Failed to load shortcut file");

    IPropertyStore* store;
    doOrDie(link->QueryInterface(IID_PPV_ARGS(&store)), "Failed to obtain PropertyStore interface");

    PROPVARIANT pv;
    doOrDie(store->GetValue(PKEY_AppUserModel_ID, &pv), "Failed to retrieve AppId");

    bool idSet = false;
    wcout << path << endl;
    if( pv.vt != VT_EMPTY ) {
        if( pv.vt != VT_LPWSTR ) {
            wcout << "Type: " << pv.vt << endl;
            exit(1);
        }

        wcout << " -> Current AppId: " << pv.pwszVal << endl;
        idSet = true;
    }
    else {
        wcout << " -> No current AppId" << endl;
    }
    PropVariantClear(&pv);

    if( !idSet ) {
        pv.vt = VT_LPWSTR;
        pv.pwszVal = name;
        wcout << "New AppId: " << pv.pwszVal << endl;

        doOrDie(store->SetValue(PKEY_AppUserModel_ID, pv), "Failed to set AppId");

        // Not sure if we need to do this
        pv.pwszVal = NULL;
        PropVariantClear(&pv);

        doOrDie(store->Commit(), "Failed to commit AppId property");
        doOrDie(file->Save(NULL, TRUE), "Failed to save shortcut");
    }

    store->Release();
    file->Release();
    link->Release();

    return true;
}

int main(int argc, LPWSTR* argv) {
    wchar_t appName[MAX_PATH], noControlShortcut[MAX_PATH], appShortcut[MAX_PATH], appData[MAX_PATH];
    wcsncpy_s(appName, L"Spotify", MAX_PATH);
    // SetCurrentProcessExplicitAppUserModelID(appName);

    HWND stepChild = FindWindow(L"Chrome_WidgetWin_0", NULL);
    HWND parent = GetParent(stepChild);
    DWORD parentD = GetWindowThreadProcessId(parent, NULL);

    if (parentD == 0) {
        if (argc > 1) {
            wcsncpy_s(appData, argv[1], MAX_PATH);
        } else {
            GetEnvironmentVariable(L"APPDATA", appData, MAX_PATH);
            lstrcat(appData, L"\\Spotify\\spotify.exe");
        }

        if( argc > 2 ) {
            wcsncpy_s(appShortcut, argv[2], MAX_PATH);
        }
        else {
            GetEnvironmentVariable(L"APPDATA", appShortcut, MAX_PATH);
            lstrcat(appShortcut, L"\\Microsoft\\Windows\\Start Menu\\Programs\\Spotify.lnk");
        }

        if (argc > 3) {
            wcsncpy_s(noControlShortcut, argv[3], MAX_PATH);
        }
        else {
            GetEnvironmentVariable(L"APPDATA", noControlShortcut, MAX_PATH);
            lstrcat(noControlShortcut, L"\\Microsoft\\Internet Explorer\\Quick Launch\\User Pinned\\TaskBar\\SpotifyNoControl.lnk");
        }

        setAppId(noControlShortcut, appName);
        setAppId(appShortcut, appName);
        wcout << appData << endl;
        LaunchSpotify(appData);
    }

    while (parentD == 0) {
        stepChild = FindWindow(L"Chrome_WidgetWin_0", NULL);
        parent = GetParent(stepChild);
        parentD = GetWindowThreadProcessId(parent, NULL);
        Sleep(100);
    }

    HWND child1 = GetNextWindow(parent, GW_HWNDPREV);
    HWND child2 = GetNextWindow(child1, GW_HWNDPREV);
    SetWindowPos(child1, (HWND)1, 0, 0, 0, 0, SWP_NOOWNERZORDER);
    SetWindowPos(child2, (HWND)1, 0, 0, 0, 0, SWP_NOOWNERZORDER);
    
    return 0;
}
```

**Comment by bernawastaken** [comment]
@JulienMaille thanks! Just wanted to take a look too see how the magic happens and maybe figure out why I'm having so many issues.

**Comment by JulienMaille** [comment]
Have a look at Win7AppId1.1.exe

**Comment by SaifAqqad** [comment]
Is it necessary to pin `SpotifyNoControl.exe` to the taskbar for it to work?
I don't pin anything to the taskbar, and running the launcher with the path of `Spotify.exe` as an argument does not work at all
If it is necessary then IMO this is a step backwards of the previous version

**Comment by JulienMaille** [comment]
Yes it is necessary for this to work. The appId can only be set on shortcuts.
My modified version of SpotifyNoControl.exe sets the Spotify shorcut and SpotifyNoControl shortcut to the same ids

**Comment by SaifAqqad** [comment]
> 
> 
> Yes it is necessary for this to work. The appId can only be set on shortcuts.
> My modified version of SpotifyNoControl.exe sets the Spotify shorcut and SpotifyNoControl shortcut to the same ids

I guess that works for a lot of people but in my case I don't want any shortcuts on either the taskbar or desktop, so I remade the original one in AHK and without the console window appearing, [here's the link if anyone's interested](https://github.com/SaifAqqad/AHK_SpotifyNoControl).

**Comment by bernawastaken** [comment]
@SaifAqqad Your new version seems to work really well for me. I am only looking for a way to combine the icons in the taskbar because I personally prefer having it that way and I'll report here once I have any info for those interested

**Comment by SaifAqqad** [comment]
@bernawastaken 
>I'm not familiar with AutoHotKey but from what I've read based on documentation and your comments in the source code it seems like it uses the Window ID to change the size 

Yeah, it uses the window handles (HWND) of spotify windows to resize them.

>Also I would like to know if it's possible to have this AHK script execute the command `spicetify auto` instead of running the spotify exe and have the same result

I just pushed a [commit](https://github.com/SaifAqqad/AHK_SpotifyNoControl/commit/c5291631bfbd2259c15c1bc040db9108e0689771) that added an extra check on the PID to make sure it belongs to `spotify.exe`, if not, it looks for a spotify process and continues on that. with this extra check, passing `"spicetify auto"` or `"C:\path\to\spicetify.exe auto"` as an argument should work.

**Comment by MarshallYTHD** [comment]
SaifAqqad's SpotifyNoControl was able to combine the icons in the taskbar but it recently stopped working. I'm assuming it could it be because of the new update?

**Comment by SaifAqqad** [comment]
@MarshallYTHD 
No I made it specifically to not have it combine the taskbar icons

You have probably been using the one @JulienMaille made

**Pull request merged**
