### PR TITLE
Neon (new theme)

### PR DESCRIPTION
**Pull request by bBSempai**
Added a new theme termed as "Neon" with 'Base' and 'Lovepink' variants.

Thank you!
[bBSempai](https://github.com/bBSempai)

### CODE REVIEW

**Comment by morpheusthewhite** [comment]
I think you can directly add those colorschemes to the existing Lovelace theme if @adriankarlen agrees

**Comment by bBSempai** [comment]
So should I just do that?

**Comment by morpheusthewhite** [comment]
Let's wait for adriankarlen reply first

**Comment by bBSempai** [comment]
brooooo @adriankarlen

**Comment by morpheusthewhite** [comment]
I think you can do it, so open another pull requests and just add and commit the new color schemes in the existing theme

**Comment by adriankarlen** [comment]
A bit late to the party, but of course that's okay :)

**Pull request closed without merging**
