### PR TITLE
DribbblishDynamic theme downloading message position fixed.

### PR DESCRIPTION
**Pull request by vangoo**

### CODE REVIEW

**Comment by morpheusthewhite** [comment]
@JulienMaille

**Comment by JulienMaille** [comment]
Is it difficult to display in on a single line at the bottom? Otherwise looks good to me

**Comment by vangoo** [comment]
> Is it difficult to display in on a single line at the bottom? Otherwise looks good to me

I want single line too but i don't know css very well. I'll happy to if did. 👍

**Comment by JulienMaille** [comment]
ok, looks good to me

**Review by morpheusthewhite — CHANGES_REQUESTED** [review]
display it on a single line at the bottom

**Comment by JulienMaille** [comment]
@morpheusthewhite I gave it a look, it's harder than expected, the text stays behind the player bar.

**Comment by morpheusthewhite** [comment]
Handle this as you prefer

**Pull request closed without merging**
