### PR TITLE
Correct class to remove vector (circle)

### PR DESCRIPTION
**Pull request by fosam**
Remove vector (circle) from input bar to allow padding to be reduced

### CODE REVIEW

**Comment by i0pt1mal** [comment]
Ahhh didnt see this I will remove my pull req real quick lmao. Also if you want to change line 266 to "visibility: hidden;" instead you can.

**Comment by fosam** [comment]
> Ahhh didnt see this I will remove my pull req real quick lmao. Also if you want to change line 266 to "visibility: hidden;" instead you can.

Instead of `opacity: 0;` you mean?

**Comment by i0pt1mal** [comment]
> > Ahhh didnt see this I will remove my pull req real quick lmao. Also if you want to change line 266 to "visibility: hidden;" instead you can.
> 
> Instead of `opacity: 0;` you mean?

Yep!

**Comment by fosam** [comment]
Accidently deleted the patch :( but created another pull req.

**Pull request closed without merging**
