### PR TITLE
Add BIB color scheme to Sleek theme

### PR DESCRIPTION
**Pull request by harbassan**
Transferring BIB-green theme in master to color scheme in Sleek theme v2.

### CODE REVIEW

**Comment by grasonchan** [comment]
I think your commit message is not good for a community-driven repository.

Nobody can know exactly what changes you have done, even which one theme. And the commit message is too much.

You can view the commit messages in the [v2 branch](https://github.com/morpheusthewhite/spicetify-themes/commits/v2).

What do you think? @morpheusthewhite

**Comment by morpheusthewhite** [comment]
I completely agree with you @grasonchan (in fact that's something I thought about as well), but the problem is that many people may not be familiar with it and I don't want it to be a barrier preventing someone from contributing. But I'm open to suggestions about this

**Comment by harbassan** [comment]
I'm sorry about that, I'm pretty new to using Github and didn't realise commit messages were global to the repository. Ill try and add more detail in the messages, and create less of them. For now though, I'm pretty sure there's nothing I can do to amend them right? Correct me if i'm wrong.

**Comment by grasonchan** [comment]
> I completely agree with you @grasonchan (in fact that's something I thought about as well), but the problem is that many people may not be familiar with it and I don't want it to be a barrier preventing someone from contributing. But I'm open to suggestions about this

Yes, it will take more time and energy.

For a community-driven repository, i think the requirements for commit messages can be relaxed. Especially for people who Poor English, just like me. 🙃

Maybe we can add a fixed structure in the Contributions of the README.md for reference. This will reduce people's learning costs and improve the readability of commit messages.

In addition, prompt the contributors try to reduce commit messages, explain "Which one theme?" and "What changes you have done?".

**Comment by morpheusthewhite** [comment]
> I'm sorry about that, I'm pretty new to using Github and didn't realise commit messages were global to the repository. Ill try and add more detail in the messages, and create less of them. For now though, I'm pretty sure there's nothing I can do to amend them right? Correct me if i'm wrong.

Actually, you can do it, give a look at `git rebase`. Or a simpler solution is `git reset <COMMIT_HASH>`, then committing again and then `git push -f`

**Comment by morpheusthewhite** [comment]
> > I completely agree with you @grasonchan (in fact that's something I thought about as well), but the problem is that many people may not be familiar with it and I don't want it to be a barrier preventing someone from contributing. But I'm open to suggestions about this
> 
> Yes, it will take more time and energy.
> 
> For a community-driven repository, i think the requirements for commit messages can be relaxed. Especially for people who Poor English, just like me. upside_down_face
> 
> Maybe we can add a fixed structure in the Contributions of the README.md for reference. This will reduce people's learning costs and improve the readability of commit messages.
> 
> In addition, prompt the contributors try to reduce commit messages, explain "Which one theme?" and "What changes you have done?".

That's a good idea, we could provide some very simple commit structure in the README while requesting people not to produce too many commits. I will think about something in the next days, thanks for the feedback

**Comment by grasonchan** [comment]
## Contributions
...
### Commit message Format

**Note: Commit only one message when you add a new theme or scheme, you can commit other messages later.**

```
<type>(<scope>): <subject>
<BLANK LINE>
<body>[optional]
```

**Any line of the commit message cannot be longer than 100 characters!**

- **type:** feat | fix | docs | chore
  - **feat:** Add a new theme or scheme | A new feature
  - **fix:** A bug fix
  - **docs:** Change the README.md or THEMES.md
  - **chore:** Add screenshots for your theme | other things
- **scope:** THEMES | ThemeName
  - THEMES is a fixed format: docs(THEMES)
  - Other situations, use your theme name
- **subject:** What changes you have done?
  - use the imperative, present tense: "change" not "changed" nor "changes"
  - don't capitalize first letter
  - no dot (.) at the end
- **body**: more details of your changes

**Example (Turntable theme):**

- feat

```
feat(Turntable): add Turntable theme
```

```
feat(Turntable): control the rotation of the turntable

Rotate the turntable by playing state.
```

- fix

```
fix(Turntable): show the cursor outside the context menu
```
- docs

```
docs(Turntable): update README.md
```

```
docs(THEMES): add preview for the Turntable
```

- chore

```
chore(Turntable): add screenshots of the Turntable
```

If you want to learn more, view the [Angular - Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines).

**Comment by morpheusthewhite** [comment]
> ## Contributions
> 
> ...
> ### Commit message Format
> 
> **Note: Commit only one message when you add a new theme or scheme, you can commit other messages later.**
> 
> ```
> <type>(<scope>): <subject>
> <BLANK LINE>
> <body>[optional]
> ```
> 
> **Any line of the commit message cannot be longer than 100 characters!**
> 
>     * **type:** feat | fix | docs | chore
>       
>       * **feat:** Add a new theme or scheme | A new feature
>       * **fix:** A bug fix
>       * **docs:** Change the README.md or THEMES.md
>       * **chore:** Add screenshots for your theme | other things
> 
>     * **scope:** THEMES | ThemeName
>       
>       * THEMES is a fixed format: docs(THEMES)
>       * Other situations, use your theme name
> 
>     * **subject:** What changes you have done?
>       
>       * use the imperative, present tense: "change" not "changed" nor "changes"
>       * don't capitalize first letter
>       * no dot (.) at the end
> 
>     * **body**: more details of your changes
> 
> 
> **Example (Turntable theme):**
> 
>     * feat
> 
> 
> ```
> feat(Turntable): add Turntable theme
> ```
> 
> ```
> feat(Turntable): control the rotation of the turntable
> 
> Rotate the turntable by playing state.
> ```
> 
>     * fix
> 
> 
> ```
> fix(Turntable): show the cursor outside the context menu
> ```
> 
>     * docs
> 
> 
> ```
> docs(Turntable): update README.md
> ```
> 
> ```
> docs(THEMES): add preview for the Turntable
> ```
> 
>     * chore
> 
> 
> ```
> chore(Turntable): add screenshots of the Turntable
> ```
> 
> If you want to learn more, view the [Angular - Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines).

Awesome. You can PR it on `v2` or I can push it

**Comment by grasonchan** [comment]
> That's a good idea, we could provide some very simple commit structure in the README while requesting people not to produce too many commits. I will think about something in the next days, thanks for the feedback

Maybe i have done it, took a few hours. (think a lot and Poor English).

@morpheusthewhite 

What do you think about it?

Is there anything need to be changes?

What else do you need to add?

**Comment by grasonchan** [comment]
> Awesome. You can PR it on `v2` or I can push it

Okay, i will PR it later.

**Comment by grasonchan** [comment]
> I'm sorry about that, I'm pretty new to using Github and didn't realise commit messages were global to the repository. Ill try and add more detail in the messages, and create less of them. For now though, I'm pretty sure there's nothing I can do to amend them right? Correct me if i'm wrong.

I think a good commit message is difficult, especially for people who Poor English, just like me.

About commit message, maybe you can refer to my comment and PR(#373), PR(#380). That's not necessarily right.

You can also refer to @harbassan and other contributors. ([v2](https://github.com/morpheusthewhite/spicetify-themes/commits/v2), [master](https://github.com/morpheusthewhite/spicetify-themes/commits/master))

**Pull request closed without merging**
