### PR TITLE
New Dribbblish Dracula Theme 

### PR DESCRIPTION
**Pull request by robbyhorvath**
Added more colors from https://draculatheme.com/contribute/ to better fit the color palette. 
image

### CODE REVIEW

**Comment by morpheusthewhite** [comment]
You need to update the screenshots too

**Comment by robbyhorvath** [comment]
Sorry, here's the updated screenshot.
 
image

**Comment by morpheusthewhite** [comment]
I mean in the Dribbblish folder

**Comment by robbyhorvath** [comment]
Whoops, my bad! Should be good now.

**Comment by khanhas** [comment]
I think this theme is nothing alike original Dracula theme and nearly identical to Horizon theme. It doesn't bring anything new to existed collection.

**Pull request closed without merging**
