### PR TITLE
Add purple variant to Black theme

### PR DESCRIPTION
**Pull request by H4kt**
I just really like dark-purple colors, so I've picked up a suitable theme and recolored it a little bit
Here is a preview of it
preview-black-purple

### CODE REVIEW

**Comment by morpheusthewhite** [comment]
tbh for me it's difficult to read the current playing song

**Comment by morpheusthewhite** [comment]
@lollilol

**Comment by H4kt** [comment]
> tbh for me it's difficult to read the current playing song

Idk how you feel about it, but as for me it seems just fine.
I just wanted to keep all colors the same
Feel free to modify their brightness, cuz I just wanted to share it with others, who might like it.

**Comment by lollilol** [comment]
> tbh for me it's difficult to read the current playing song

what should i do about it lol

**Comment by morpheusthewhite** [comment]
I was implicitely asking if it's ok for you to merge it (eventually after fixing that color)

**Comment by lollilol** [comment]
yea, imma review it and test a little bit

**Comment by lollilol** [comment]
image
i like it more this way
```[Purple]
main_fg                               = FFFFFF
secondary_fg                          = DEDEDE
main_bg                               = 000000
sidebar_and_player_bg                 = 000000
cover_overlay_and_shadow              = 000000
indicator_fg_and_button_bg            = 6102a0
pressing_fg                           = FF5C86
slider_bg                             = 2c2a30
sidebar_indicator_and_hover_button_bg = 710cb4
scrollbar_fg_and_selected_row_bg      = 0e0e0e
pressing_button_fg                    = DEDEDE
pressing_button_bg                    = 383145
selected_button                       = 7419ca
miscellaneous_bg                      = 1d1a21
miscellaneous_hover_bg                = 7419ca
preserve_1                            = FFFFFF
```

**Comment by morpheusthewhite** [comment]
It's better also for me, if you want you can push it here @lollilol

**Comment by lollilol** [comment]
There is one thing in this theme i cant fix cuz im not a pro when it comes to css. [Line 30](https://github.com/morpheusthewhite/spicetify-themes/blob/f0b3b5856a4bd54696ec994a623b991e2f477674/Black/user.css#L130) makes it so that you can only really switch the cover to the bigger thing when clicking here
image
and the size of the seekbar makes it unclickable.
And when i remove this css block, it makes the seekbar go really small. Anyway to fix this?

**Comment by morpheusthewhite** [comment]
Try `z-index` to raise the element above the one that covers it

**Pull request merged**
