### PR TITLE
Add Tidal theme

### PR DESCRIPTION
**Pull request by FivePixels**
Here's my theme based off of Tidal. I thought I'd add, I started a Discord server for Spicetify https://discord.gg/AmUdJYyGvt. Feel free to join.

### CODE REVIEW

**Comment by morpheusthewhite** [comment]
I noticed just now the preview of your theme looks quite bad on some screens, can you add a screenshot or replace the .gif?

**Comment by FivePixels** [comment]
> I noticed just now the preview of your theme looks quite bad on some screens, can you add a screenshot or replace the .gif?

The screenshots look a bit blurry until I click on them, not sure why.

**Comment by morpheusthewhite** [comment]
I will add it myself then

**Comment by FivePixels** [comment]
> 
> 
> I will add it myself then

Weird, looking at the GIF on Windows is much different than the one that shows up on macOS. I'll change out the GIF asap.

**Pull request merged**
