### PR TITLE
add an Xresources theme

### PR DESCRIPTION
**Pull request by devcroc**
A Spicetify theme which follow Xresources colors + an accent color

### CODE REVIEW

**Comment by devcroc** [comment]
I'm sorry, I've missed some of your guidlines, I apologize.
Beside, here's what the commit message should have been :

feat(Xresources): add Xresources theme

use Xresources colors + an accent color

**Comment by morpheusthewhite** [comment]
What are the major changes in the UI with the respect to BurstSienna? It looks quite similar

**Comment by devcroc** [comment]
The UI is indeed quite the same, no changes here. 
The changes are only about colors which follows `~/.Xresources` + an accent color you define in `colors.ini` (only for linux users). 

The purpose is only to use the same colors defined in a system wide fashion, as many applications can reuse Xresources colors, and better integrate in the system respecting the color scheme a user choose (with pywal for example).

**Comment by morpheusthewhite** [comment]
Then I would suggest creating another folder in `_Extra`, named `Xresources` with a `README.md` in it where you add the colour scheme based on Xresources and explain it

**Pull request closed without merging**
