### PR TITLE
[Dribblish/DribblishDynamic] fix "liked songs" sidebar icon.

### PR DESCRIPTION
**Pull request by AvinashReddy3108**
Here's how it looks after the changes.

A heart, as it should be!

### CODE REVIEW

**Comment by khanhas** [comment]
No, sorry. spicetify-cli and Dribbblish were made customizable. Users who find what doesn't seem fit to their style, they can make the change themselves. We don't need to make change a small little thing that's not critical bug.
I don't know about DribbblishDynamic, I will let the author decide.

**Comment by AvinashReddy3108** [comment]
> No, sorry. spicetify-cli and Dribbblish were made customizable.

Ok. :eyes: 

> Users who find what doesn't seem fit to their style, they can make the change themselves. We don't need to make change a small little thing that's not critical bug.

I think you misunderstood me.
This PR is not made because it does not fit my style, but to increase accessibility (by reducing confusion) by using the correct (or ["best for the purpose"](https://github.com/morpheusthewhite/spicetify-themes/blob/master/DribbblishDynamic/dribbblish-dynamic.js#L90-L113)) icons.

> I don't know about DribbblishDynamic, I will let the author decide.

Sure :smile:

**Comment by JulienMaille** [comment]
I like it. I have to admit I'm sometime lost with default icons

**Comment by morpheusthewhite** [comment]
I guess that if khanhas doesn't want this change on his theme we can close this

**Pull request closed without merging**
