### PR TITLE
[Dribbblish] Center background images of playlists in the sidebar

### PR DESCRIPTION
**Pull request by DuckerDuck**

### CODE REVIEW

**Comment by khanhas** [comment]
Okay! Thank you for your contribution.
@JulienMaille he pulled request on DribbblishDynamic too. Just hit merge if you vibe with this.

**Comment by JulienMaille** [comment]
I can't see any difference, care to share a before/after picture?

**Comment by DuckerDuck** [comment]
Seems like it does not affect every picture, but here is the before/after screenshot:

image

**Comment by JulienMaille** [comment]
Thank you @DuckerDuck

**Pull request merged**
