### PR TITLE
[DribblishDynamic] Fix some icons in the left toolbar.

### PR DESCRIPTION
**Pull request by AvinashReddy3108**
Since we [use a loop to update colors in iframes](https://github.com/morpheusthewhite/spicetify-themes/commit/cc79cac0490f2838c0f28bdacdf0b3ac40e2678d#diff-01a159eaff5d6d94de2354cdc9a1c690d8fcf76308a5ef63c158734c1f2b4b99L275-R279) now, we can get rid of manually updating colors of hardcoded iframes.

Screenshot_20210214_211526
Screenshot_20210214_212845

- Also fixed left toolbar icons for `Reddit`, `Made for you` and `Recently Played` sections.

	Their positions (from the top) are in brackets:

	- Reddit (5th)
	- Made for you (7th)
	- Recently Played (8th)

### CODE REVIEW

**Comment by AvinashReddy3108** [comment]
Tagging @JulienMaille (maintainer) for review.

**Comment by JulienMaille** [comment]
What about using that one for recently played?
image

```css
.spoticon-paymenthistory-16::before {
  content: "\f24A";
  font-size: 16px;
}
```

**Comment by JulienMaille** [comment]
> Since we [use a loop to update colors in iframes

Do you have any idea why this generates so many `Uncaught TypeError: n[o].postMessage is not a function` errors?

**Comment by AvinashReddy3108** [comment]
> > Since we [use a loop to update colors in iframes
> 
> Do you have any idea why this generates so many `Uncaught TypeError: n[o].postMessage is not a function` errors?

Unfortunately no, I'm very new to JS.

**Comment by AvinashReddy3108** [comment]
> What about using that one for recently played?
> image
> 
> ```css
> .spoticon-paymenthistory-16::before {
>   content: "\f24A";
>   font-size: 16px;
> }
> ```

- The one I used makes more sense to me.
- The icon name I used was in the available options specified

> What about using that one for recently played?
> image
> 
> ```css
> .spoticon-paymenthistory-16::before {
>   content: "\f24A";
>   font-size: 16px;
> }
> ```

- The one in this PR makes more sense to me. :thinking: 
- The icon name was available in the options [here](https://github.com/AvinashReddy3108/spicetify-themes/blob/patch-2/DribbblishDynamic/dribbblish-dynamic.js#L89-L110), unlike the one you are suggesting.

**Comment by JulienMaille** [comment]
Hmmm, ok.
Have a look at https://fontdrop.info/
You can drop the `spoticon` file found in `%UserProfile%\.spicetify\Extracted\Raw\glue-resources\fonts\`

**Comment by morpheusthewhite** [comment]
@JulienMaille what does this PR needs before being merged?

**Comment by JulienMaille** [comment]
A before/after screenshot of the modified icons and some user feedback in order to verify the changes do make sense.

**Comment by AvinashReddy3108** [comment]
> A before/after screenshot of the modified icons and some user feedback in order to verify the changes do make sense.

We already have screenshots of the before/after, [have a look here](https://github.com/morpheusthewhite/spicetify-themes/pull/272#issue-573109755).

**Comment by JulienMaille** [comment]
Sorry both screenshots show the after, correct? Some of those icons require plugins I don't have (like reddit) that's why I would like to see how it looks before your changes. Can you kindly show me? THanks

**Comment by AvinashReddy3108** [comment]
> Sorry both screenshots show the after, correct? Some of those icons require plugins I don't have (like reddit) that's why I would like to see how it looks before your changes. Can you kindly show me? THanks

Ah, yes.. my bad (both are the "after" screenshots)

**Comment by JulienMaille** [comment]
Ok so here is what you want to change:
@morpheusthewhite @khanhas do you feel like the new icons are better?
image

**Comment by JulienMaille** [comment]
@AvinashReddy3108 What is the 4th (clock) icon for? It's a duplicate of the recently played icon in 8th position.

**Comment by AvinashReddy3108** [comment]
> @AvinashReddy3108 What is the 4th (clock) icon for? It's a duplicate of the recently played icon in 8th position.

Recently played (History)
https://github.com/einzigartigerName/spicetify-history

**Comment by morpheusthewhite** [comment]
> Ok so here is what you want to change:
> @morpheusthewhite @khanhas do you feel like the new icons are better?

Maybe the reddit icon could be better, but I'm not sure about the others as the "Made for you" is replaced by a generic music icon and the new "Recently played" icon is less intuitive for me. What I would suggest is to keep the reddit and use the circular arrow icon for the Recently played (history) in order to avoid the icon clash

**Comment by JulienMaille** [comment]
@AvinashReddy3108 can you try my latest commit and share a screenshot? I added custom icons for reddit and recently-played

**Pull request closed without merging**
