### PR TITLE
Better look to Flatten theme

### PR DESCRIPTION
**Pull request by ref**
remove gradient background in the search page; remove border in the track list; fix hidden tracks color on track list; add red color to heart.

Look comparison on my screenshots. 

before
before-1

after
after-1

before
before-2

after
after-2

### CODE REVIEW

**Comment by morpheusthewhite** [comment]
@qwersteve07

**Comment by ref** [comment]
Guys, i added a few more changes.

Change green color to Spotify color from official guideline.
Change EXPLICIT foreground color (less bright). 
Change color for dislike button (were previously not visible).

Perfect look now:
Screenshot 2020-10-09 at 15 47 38

**Comment by qwersteve07** [comment]
hello @ref thx for the contribution!
The changes looks nice, and on the Like button style, since this theme is only for spotify main color and black-white, it would be a great help if you can change the color from red to spotify green!

**Comment by ref** [comment]
@qwersteve07 thanks for your review! I changed the button color to official green.

**Review by morpheusthewhite — CHANGES_REQUESTED** [review]
Please update the screenshot too

**Review by morpheusthewhite — APPROVED** [review]

**Pull request merged**
