### PR TITLE
Inital addition of Coral and CherryBlossom Themes

### PR DESCRIPTION
**Pull request by toby-wong**
Added two new themes, Coral and CherryBlossom.

### CODE REVIEW

**Comment by morpheusthewhite** [comment]
I was thinking just now: why not adding them as a single theme with 2 different color scheme? (Like Vaporwave)

**Comment by toby-wong** [comment]
I sperated them simply due to the fact CherryBlossom was a theme a friend specifically asked me to create for their wallpaper.

**Comment by morpheusthewhite** [comment]
Yeah that's not a problem, he can still select the color theme and so switch between the 2

**Comment by morpheusthewhite** [comment]
I suggest this because they are very similar, so to diminish the number of folders of the project which is currently growing fastly

**Comment by morpheusthewhite** [comment]
I merged them into only one theme with 2 different color schemes, CherryBlossom

**Pull request merged**
