### PR TITLE
add Gruvbox color for Kaapi theme

### PR DESCRIPTION
**Pull request by Antoine-Derouin**
Hi @Jom97 , I took your work as a basis for applying the Gruvbox colour palette :
https://github.com/morhetz/gruvbox-contrib

But I couldn't find where the color of "preserve_1" is applied.

gruvbox-spoty

### CODE REVIEW

**Comment by Jom97** [comment]
> But I couldn't find where the color of "preserve_1" is applied.

I don't think "preserve_1" is used anywhere. I just left it in, just in case.

>Hi @Jom97 , I took your work as a basis for applying the Gruvbox colour palette :
https://github.com/morhetz/gruvbox-contrib

I'm fine with merging these changes. But i don't have the write access. Also I think it'll be a good idea to create your own theme if you plan on further developing your theme.

**Comment by morpheusthewhite** [comment]
I agree, if you plan further development I think it's better to create another one, otherwise just keep it like that

**Comment by Antoine-Derouin** [comment]
@Jom97 @morpheusthewhite 

I might maybe make a new theme later.

In first time, just adding an alternative palette is already satisfying!

I'll let you judge if you want to merge or not.

**Comment by Jom97** [comment]
Yeah i'd like to merge this.

**Pull request merged**
