### PR TITLE
OnePunch - BeachPalette adapted

### PR DESCRIPTION
**Pull request by maxseidlitz**
**I hope you like my theme**. Thanks for that amazing app ! Having so much fun with css right now.
`Sorry for those endless commits, its my first time forking a project.`

### CODE REVIEW

**Comment by morpheusthewhite** [comment]
Change the theme name to follow the convention please

**Comment by morpheusthewhite** [comment]
Also I think you should change the white of the 3 dots in the top left corner and the light green of the shuffle, they are not easy to read

**Comment by morpheusthewhite** [comment]
And also slightly increase the constrast of the foreground green

**Comment by maxseidlitz** [comment]
okay ill hand u the new version tomorrow. thanks for the feedback.

**Comment by JulienMaille** [comment]
> Also I think you should change the white of the 3 dots in the top left corner and the light green of the shuffle, they are not easy to read

Is there a way to change the 3 white dots color? Doesn't seem to be an "html" component.

**Comment by morpheusthewhite** [comment]
```html
<button type="button" data-button="contextmenu" class="button button-icon-only button-more" data-tooltip="More" data-log-data="{ &quot;index&quot;: , &quot;target_uri&quot;: &quot;spotify:row:ac36ce5c4fc4c984:spotify:track:0PAXhtBfNQVZ6n0ge2BUJW&quot; }" data-interaction-target="context-menu-button" data-interaction-intent="show-options"></button>
```

**Comment by morpheusthewhite** [comment]
> Is there a way to change the 3 white dots color? Doesn't seem to be an "html" component.

Actually I don't even have them (just updated Spotify)

**Pull request closed without merging**
