### PR TITLE
Update the Dribbblish theme with a nord Variant

### PR DESCRIPTION
**Pull request by Lunchb0ne**
Hopefully, it looks good :)

### CODE REVIEW

**Comment by khanhas** [comment]
There is only one Nord, why even bother named it "nord-dark"

**Comment by Lunchb0ne** [comment]
Might add the light version in a few days

**Comment by Lunchb0ne** [comment]
Added The Light Version

**Comment by morpheusthewhite** [comment]
> Added The Light Version

Add a screenshot per color scheme

**Comment by Lunchb0ne** [comment]
Done, I don't have a widescreen so the screenshots are kinda off from the original one 😅

**Pull request merged**
