### PR TITLE
Koushi theme v2

### PR DESCRIPTION
**Pull request by yougotwill**
This is the version 2 of my Koushi theme which has a PR for the old Spotify UI here https://github.com/morpheusthewhite/spicetify-themes/pull/345.

## Important UI Changes

- Outlines all major UI Elements (General screen, Device Menu, Context Menus, etc.) in Spotify with an alternative color. i.e Dark theme white outlines, Light theme black outlines.
- Toggles UI Colors based on macOS's System appearance automatically.

### Dark theme (default)

dark theme

### Light theme

light theme

### CODE REVIEW

**Comment by morpheusthewhite** [comment]
What are the differences from the default theme?

**Comment by morpheusthewhite** [comment]
I think it is still very similar to the default theme, I would suggest pushing the color schemes to the existing `Default` theme.

**Comment by morpheusthewhite** [comment]
> I think it is still very similar to the default theme, I would suggest pushing the color schemes to the existing `Default` theme.

This is also the reason why I wasn't sure about merging your previous PR

**Comment by yougotwill** [comment]
Hey @morpheusthewhite thanks for your response. I guess adding outlines to everything isn't much of a cosmetic change but I thought having the color scheme that changes based on system appearance (it's hard coded in) would be a breaking change to the Default theme since normally you just choose a single color scheme and it won't change without you changing the `config.ini` file directly?

I'll leave the PR here but continue doing my own thing on my own repo. If you feel the PR isn't enough to have a separate theme from the Default feel free to close and no hard feelings :)

**Comment by yougotwill** [comment]
Same thing for my other PR. If you feel it's not enough feel free to close it.

**Comment by morpheusthewhite** [comment]
I don't use MacOS so I don't really know how much that could be useful, I'll wait for some feedback before deciding

**Comment by morpheusthewhite** [comment]
Not too many people seem interested in this theme. I will close. 

Thanks for the PR, anyway.

**Pull request closed without merging**
