### PR TITLE
Added a Nord theme

### PR DESCRIPTION
**Pull request by ahsan-a**
This theme includes colour changes along with a lot of UI changes that also change the feel of spotify, including different rounding, custom font colours, css filters on Spotify-green gifs etc. 

__Home
__Playlist

### CODE REVIEW

**Comment by morpheusthewhite** [comment]
What do you mean by "Spotify-green gifs"?

**Comment by ahsan-a** [comment]
on the new spotify, there’s a little visualiser gif next to your current playing song on a playlist. However, by using CSS filters, i was able to change that gif to black, and then nord0. This is in the `.main-trackList-playingIcon` class in my user.css.

**Comment by morpheusthewhite** [comment]
Sorry, I think this still looks quite similar to the Default theme, you can PR the colour scheme on that theme, as I guess many people may want to use it.

**Comment by ahsan-a** [comment]
understandable- thank you for maintaining this monolith of a repo and creating a hub for people to share and get new themes

**Comment by morpheusthewhite** [comment]
Thank you for the Pull Request

**Pull request closed without merging**
