### PR TITLE
Creation of Discord theme for Spicetify

### PR DESCRIPTION
**Pull request by DavoMyan**
Hi all!

I created a Spicetify theme inspired by Discord's UI, uses discord's main colors.

Hope you enjoy it :)

### CODE REVIEW

**Comment by DavoMyan** [comment]
How is my theme similar to onedarkish? 🤔

**Comment by morpheusthewhite** [comment]
If you just changed the color scheme please open another pull request in which you just add your scheme to the existing OneDarkish

**Comment by DavoMyan** [comment]
> If you just changed the color scheme please open another pull request in which you just add your scheme to the existing OneDarkish

But I didn't copy from OneDarkish or anything else to change a color scheme.

Also I see many different themes that look like each other with only the colors changed, which I pretty much did, but I never touched the files of onedarkish

**Comment by DavoMyan** [comment]
image
Also this is weird, ctrl+f in my files says it finds the word onedarkish 3 times, but doesn't actually show where? (see sidebar, no ''found'' segments)

**Comment by morpheusthewhite** [comment]
> But I didn't copy from OneDarkish or anything else to change a colour scheme.
> 
> Also I see many different themes that look like each other with only the colours changed, which I pretty much did, but I never touched the files of onedarkish

If you see themes with the same appearance they actually have small differences (the `user.css` are different)

What I'm saying is that it's ok to add a new colour scheme, but since the only difference between your theme and OneDarkish are the colours, then it's better to just keep one folder with both colour schemes (I'm not saying that you changed OneDarkish). Right?

**Comment by morpheusthewhite** [comment]
> image
> Also this is weird, ctrl+f in my files says it finds the word onedarkish 3 times, but doesn't actually show where? (see sidebar, no ''found'' segments)

I'm not sure, maybe the search checks in other tabs of the GitHub page too (so it finds it in Conversation)

**Comment by DavoMyan** [comment]
> > But I didn't copy from OneDarkish or anything else to change a colour scheme.
> > Also I see many different themes that look like each other with only the colours changed, which I pretty much did, but I never touched the files of onedarkish
> 
> If you see themes with the same appearance they actually have small differences (the `user.css` are different)
> 
> What I'm saying is that it's ok to add a new colour scheme, but since the only difference between your theme and OneDarkish are the colours, then it's better to just keep one folder with both colour schemes (I'm not saying that you changed OneDarkish). Right?

I'm sorry I'm not sure I understand, I could say the same about Dark, Dobbo, Deepcoral, OneDarkish, they all look the same with different colors and I copied nothing over from anything (only the css file from spicetify).

Ok I just checked, because I have copied spicetify's css file it is saying it's a duplicate of onedarkish because onedarkish is also using the exact same css file. I have removed the duplicate css code and it passes the checks now.

**Comment by morpheusthewhite** [comment]
> I'm sorry I'm not sure I understand, I could say the same about Dark, Dobbo, Deepcoral, OneDarkish, they all look the same with different colours and I copied nothing over from anything (only the CSS file from spicetify).

I checked it with `diff -b` and they have different CSS files though

> Ok I just checked, because I have copied spicetify's CSS file it is saying it's a duplicate of onedarkish because onedarkish is also using the exact same CSS file. I have removed the duplicate CSS code and it passes the checks now.

You're right.

**Comment by morpheusthewhite** [comment]
Anyway, what I meant you do is just adding your colour scheme to OneDarkish (like done [here](https://github.com/morpheusthewhite/spicetify-themes/pull/171) for example)

**Comment by DavoMyan** [comment]
> Anyway, what I meant you do is just adding your colour scheme to OneDarkish (like done [here](https://github.com/morpheusthewhite/spicetify-themes/pull/171) for example)

But my theme has no association with onedarkish and I don't want to because I want my own folder where I can put other alternatives in like a light mode

**Comment by DavoMyan** [comment]
I've decided I will make my own CSS changes, so its a tad different than the rest. I will let you know once I'm done.

**Comment by DavoMyan** [comment]
Should be now how you wanted.

But I see so many similar themes, where it looks like as if the only thing that's changed are the colors, are they still passable because their CSS is slightly different?

Thanks btw.

**Comment by morpheusthewhite** [comment]
> Should be now how you wanted.
> 
> But I see so many similar themes, where it looks like as if the only thing that's changed are the colors, are they still passable because their CSS is slightly different?
> 
> Thanks btw.

I should check myself to see if differences are noticeable/important and that's something I don't have the time to do, so I guess this is the best compromise for now (if you have suggestions for that they are welcome)

**Comment by morpheusthewhite** [comment]
Considering also that I don't want theme folders to proliferate without it being needed

**Pull request merged**
