### PR TITLE
Added support for spicetify_v2 (New spotify UI)

### PR DESCRIPTION
**Pull request by okarin001**
Here you go...It's done I guess... (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧

- Added dark/light mode schemes
- changed to the new Spotify UI
- removed that icon shit I was doing.

I couldn't add screenshots. My photoshop is shitting right now. Anyone wants to contribute!! or I'll add it later. (×﹏×)

### CODE REVIEW

**Comment by morpheusthewhite** [comment]
You should open a PR for the v2 branch, not for the master (for this reason I will close the PR).

Also, you don't need to leave legacy files, they are and will be available in another branch.

**Comment by okarin001** [comment]
my bad....I'll fix it. thanks

**Comment by okarin001** [comment]
@morpheusthewhite sorry to bother you. I can't push to v2 branch, I tried pushing to master and creating a PR on v2 that doesn't work. I'm a GitHub noob, may you suggest me what to do!!

**Comment by morpheusthewhite** [comment]
Your forked repository should have another branch, `v2`, which is missing, where should push these new changes. Try with
https://stackoverflow.com/questions/50220114/how-do-i-sync-all-new-upstream-branches-with-my-fork

**Comment by okarin001** [comment]
> Your forked repository should have another branch, `v2`, which is missing, where should push these new changes. Try with
> https://stackoverflow.com/questions/50220114/how-do-i-sync-all-new-upstream-branches-with-my-fork

Thanks a lot. I did it finally

lol

**Pull request closed without merging**
