### PR TITLE
refactor(Turntable): support new Spotify UI, control the rotation of the turntable

### PR DESCRIPTION
**Pull request by grasonchan**
Hi.

This is the new version for spicetify v2. It's completed now.

It's based on Spotify original theme.

## Important Changes

- navbar, global topbar, search input
- global playlist
  - remove gradient in the header
  - use linear gradient design in the playlist
- now playing bar
  - cover image and "expand & collapse" button
  - position of playback bar
- blur modal backdrop
- Full App Display
  - redesign
  - response
  - control the rotation of the turntable

## Preview

turntable

full app display

full app display - vertical mode

### CODE REVIEW

**Comment by grasonchan** [comment]
I have two questions:

1. My theme includes extensions, need to explain in the READNE?
like this
image

2. Need to add to #368 ?

**Comment by morpheusthewhite** [comment]
> I have two questions:
> 
>     1. My theme includes extensions, need to explain in the READNE? like this
> 
> 
> image
> 
>     1. Need to add to #368 ?

Yes, probably it helps people who want to install it

**Comment by morpheusthewhite** [comment]
Also, I think it would be nice if you could add a gif with the rotating effect

**Comment by grasonchan** [comment]
> Also, I think it would be nice if you could add a gif with the rotating effect

Yep, i think so too.

I tired it for a long time, but the GIF effect is bad. 😔

This is a video preview, you can see the effect is no very good, and the GIF is too bad.

https://user-images.githubusercontent.com/19476925/119309867-7e522000-bca1-11eb-9bcb-e4ca98582bf7.mov

**Comment by morpheusthewhite** [comment]
> > Also, I think it would be nice if you could add a gif with the rotating effect
> 
> Yep, i think so too.
> 
> I tired it for a long time, but the GIF effect is bad. pensive
> 
> This is a video preview, you can see the effect is no very good, and the GIF is too bad.
> 2021-05-23.01.40.17.mov

I think it's fine

**Comment by grasonchan** [comment]
> I think it's fine

I made a GIF, but it looks really too bad. What do you think?

rotate_turntable

**Comment by morpheusthewhite** [comment]
> > I think it's fine
> 
> I made a GIF, but it looks really too bad.
> 
> I think a clear picture will be more attractive than this GIF. What do you think?
> 
> rotate_turntable

I think the video was fine since showing it in the preview of the themes gives a better idea of the theme than the single image. But it's up to you to decide which one to show in THEMES.md

**Comment by grasonchan** [comment]
@morpheusthewhite Yes, video preview is better.

I recorded a video for this.

I don't want to put it in the repository, because it will make the repository heavier.

I think this video can be link in the README.md.

https://user-images.githubusercontent.com/19476925/119483404-84223100-bd87-11eb-8dfa-5af9f7a2e925.mov

**Comment by morpheusthewhite** [comment]
What about this gif?

turntable

**Comment by grasonchan** [comment]
> What about this gif?
> 
> turntable

Thank you, it is better than what i made.

But GIFs is not better than videos because it has been compressed. And i hope to show its exquisiteness.

**Comment by morpheusthewhite** [comment]
I see. 

Because one of the reasons for which I prefer GIFs is that they automatically start playing. Maybe you could make GitHub autoplay the video with some HTML code

**Comment by grasonchan** [comment]
> I see.
> 
> Because one of the reasons for which I prefer GIFs is that they automatically start playing. Maybe you could make GitHub autoplay the video with some HTML code

Maybe GitHub does not support video autoplay.

image

image

**Pull request merged**
