### PR TITLE
Add Dribbblish Nord-Superdark to match other Nord themes

### PR DESCRIPTION
**Pull request by kallekalle**
Add a Dribbblish Nord-Superdark theme (#3B4252 sidebar and whiter sidebar text) to match the BetterDiscord Nordic theme and the Nord Windows Theme

### CODE REVIEW

**Comment by morpheusthewhite** [comment]
Please also add the preview in THEMES.md

**Review by morpheusthewhite — CHANGES_REQUESTED** [review]
Please also add the preview in THEMES.md

**Comment by kallekalle** [comment]
Should be done now, my bad lol

Den tir. 24. aug. 2021 kl. 09.27 skrev morpheusthewhite <
***@***.***>:

**Review by morpheusthewhite — APPROVED** [review]

**Comment by katawajojo** [comment]
Not to be that guy, but I literally did this same thing before, and was rejected. What's changed?

#327

**Comment by morpheusthewhite** [comment]
> Not to be that guy, but I literally did this same thing before, and was rejected. What's changed?

Nothing, khanhas closed your pr and he didn't reply to this one yet. He will decide if it's ok or not (my approval is not really meaningful here)

**Comment by morpheusthewhite** [comment]
image

You should choose colors that are more distinguishable for these elements

**Comment by kallekalle** [comment]
Like white? Orrr

ons. 6. okt. 2021 kl. 19.11 skrev morpheusthewhite ***@***.***

**Comment by khanhas** [comment]
Appreciate your contribution. But sorry, Dribbblish has enough color schemes.

**Pull request closed without merging**
