### PR TITLE
OldSpotify

### PR DESCRIPTION
**Pull request by vegetaalex66**
Let me know if I did something incorrectly, I don't fully grasp Github yet x)

### CODE REVIEW

**Comment by morpheusthewhite** [comment]
Did you try applying it to the new Spotify version?

**Comment by khanhas** [comment]
... What the?
Just turn off `inject_css` and `replace_colors` if you want original spotify layout.

**Comment by morpheusthewhite** [comment]
> ... What the?
> Just turn off `inject_css` and `replace_colors` if you want original Spotify layout.

I think he would like to the create a theme with the old UI look (as recently Spotify hugely changed its look)

**Comment by vegetaalex66** [comment]
> 
> 
> > ... What the?
> > Just turn off `inject_css` and `replace_colors` if you want original Spotify layout.
> 
> I think he would like to the create a theme with the old UI look (as recently Spotify hugely changed its look). But I'm not sure this will do the work

I'm not sure if I misunderstand what you mean by "applying it the new Spotify version", but this does work. Applying my theme to Spotify (post update) changes its UI back to how it was before the update, as per my uploaded screenshot. The only things that I noticed I was not capable to change are the background color of the playlist scrollbar and the header.

**Comment by vegetaalex66** [comment]
> 
> 
> ... What the?
> Just turn off `inject_css` and `replace_colors` if you want original spotify layout.

Hi khanhas, thank you for your feedback. If this does revert Spotifys UI to its old state, even more closely than my theme does, please ellaborate on how exactly I do the things you have listed. What I accomplished thus far I did by trying out other themes, looking through stuff with the devtools and copy & pasting my changes from there to the user.css. Took me the whole evening basically. So turning off inject_css is not exactly something I know how to do.

**Comment by khanhas** [comment]
By turning off I mean editing your config file (run `spicetify -c` to know where config file locates at)
New Spotify UI is automatically discarded by spicetify. If you're using latest spicetify, it's not possible to see or switch to new Spotify UI. Therefore your theme is obsolete.

**Comment by vegetaalex66** [comment]
> 
> 
> By turning off I mean editing your config file (run `spicetify -c` to know where config file locates at)
> New Spotify UI is automatically discarded by spicetify. If you're using latest spicetify, it's not possible to see or switch to new Spotify UI. Therefore your theme is obsolete.

Well shit, there goes my Friday evening. I didn't know you could do that, I believed only the white default spicetify theme or custom ones were possible. Thanks for clarifying, I'm happy to have the old UI 100% restored now.

**Pull request closed without merging**
