### PR TITLE
Added 2 alternatives version to ShadowCustom

### PR DESCRIPTION
**Pull request by rodlessa**
Added ShadowCustom-S, ShadowCustom with a smaller player everything else stays the same.
Added a ShadowCustom-S-Nord, basically ShadowCustom with nord inspired color palette.

### CODE REVIEW

**Comment by morpheusthewhite** [comment]
@CallMeVorex

**Comment by morpheusthewhite** [comment]
If those themes are the same except for the colors you should include them in the same folder and use them as differentl color schemes, as done for the Vaporwave theme

**Comment by rodlessa** [comment]
The color schemes does change but theres also the size of the player i will submit another version with nord color scheme into the main ShadowCustom and leave a secondary user.css with the smaller player

**Comment by morpheusthewhite** [comment]
In my opinion having 2 different `user.css` in the same theme is something which may not be clear and, as far as I know, each one who wanted to switch between them should rename the file. That's why I think only one of them should be kept. 

If @CallMeVorex agrees with your changes then the one of 2 version will be kept

**Comment by CallMeVorex** [comment]
@morpheusthewhite lots of stuff was deleted that you guys have requested to commit so i cannot check what you have changed, summarise exactly what you ideas where to change to my custom theme?

**Comment by rodlessa** [comment]
@CallMeVorex Sorry about all thoose commits, i did a bunch because i was thinking having different themes and end up forgetting a few details, basically, i change the size of the player, thats why another `user.css`, the second change was adding a nord like theme on the `color.ini`. Here's the nord themed with the small player.

https://raw.githubusercontent.com/rodlessa/spicetify-themes/master/ShadowCustom/ShadowCustom-S-Nord.png

**Comment by CallMeVorex** [comment]
@morpheusthewhite Ah i see now looks good! There are some bugs with my version espeically with screen resolution, i decided to make the theme on a 1920x1080 monitor and stuggles to adapt to resolution changes thats the only problems i have encountered. If your knowledge with these themes and css is better than mine then feel free to tweak around with the code and see if you can make the theme responsive to different resolution types.

**Comment by morpheusthewhite** [comment]
So do you agree to use the new css? This will replace yours

**Comment by morpheusthewhite** [comment]
@CallMeVorex

**Comment by morpheusthewhite** [comment]
I decided not merge this since I think the original style of the theme is pretty peculiar. I'd instead prefer to have another theme instead of another `user-s.css` which is a little strange

**Pull request closed without merging**
