### PR TITLE
NewPlaylistButton now hidden again.

### PR DESCRIPTION
**Pull request by doubletruth**

### CODE REVIEW

**Comment by morpheusthewhite** [comment]
Can you provide a screenshot of the change you've made in the application interface?

**Comment by doubletruth** [comment]
From the code, it is clear that it was intended that the New Playlist Button is meant to be removed as part of the theme. For whatever reason, that specific code element's name has since changed.

old
new

**Comment by morpheusthewhite** [comment]
That line is present in a lot of different themes, nonetheless in almost all screenshots the button is visible (look for example at Pop-Dark or at Elementary). So probably they did not care about it

**Comment by morpheusthewhite** [comment]
@rien333 what is your idea?

**Comment by doubletruth** [comment]
@morpheusthewhite In the comments of the file, the author specifically writes 
> /*Hide some annoying elements like profile name and pic, upgrade button and device connect bar at bottom, new playlist button*/
which clearly shows that they intended to remove it. Furthermore, there is no element within the Spotify default theme named 'NewPlaylistButton' but only 'NewPlayListButton__button' hence the PR.

**Comment by rien333** [comment]
Personally, I like it without the button (too big for how often I guess anyone wants to make a new playlist), but I'm not a hardcore spotify user. 

As you already said, the line question is indeed just a line that is/was present by default in the spicetify `user.css` file - hence why it's present in virtually all other themes. @doubletruth  If you think the spicetify author made a mistake, you should open an issue there. 

That said, I've been trying to remove a lot of stuff from the spotify UI as well, given that I really don't use it for anything other  than to the search for and listen to albums I've found elsewhere. I've been hesitant to upload it though, because my use case is quite limited. Nevertheless, it might be nice to have an example heavily modified `user.css` file to showcase what's possible. Users can still easily copy over a `user.css` file from another theme. Or I could upload it as a new theme `nord-minimal`. 

I forgot what else I changed, but I did remove the sidebar in full:

**Comment by morpheusthewhite** [comment]
> > Hide some annoying elements like profile name and pic, upgrade button and device connect bar at bottom, new playlist button
> 
> which clearly shows that they intended to remove it. Furthermore, there is no element within the Spotify default theme named 'NewPlaylistButton' but only 'NewPlaylistButton__button' hence the PR.

Again, this is part of lot of themes. As was said, this is probably because they were all created starting from the default theme.

Nonetheless I'll merge this PR, following @rien333's suggestion

**Comment by morpheusthewhite** [comment]
> That said, I've been trying to remove a lot of stuff from the spotify UI as well, given that I really don't use it for anything other than to the search for and listen to albums I've found elsewhere. I've been hesitant to upload it though, because my use case is quite limited. Nevertheless, it might be nice to have an example heavily modified `user.css` file to showcase what's possible. Users can still easily copy over a `user.css` file from another theme. Or I could upload it as a new theme `nord-minimal`.

Yes, if you think there are interesting differences you can open a PR as NordMinimal or whatever you want to call it

**Comment by morpheusthewhite** [comment]
@khanhas I think you should fix it in the default theme

**Pull request merged**
