### PR TITLE
Adding Dreary Theme

### PR DESCRIPTION
**Pull request by CharlieS1103**
This is way too messy at that point, considering just making another repository entirely instead of squashing

### CODE REVIEW

**Comment by morpheusthewhite** [comment]
> This is way too messy at that point, considering just making another repository entirely instead of squashing

I would suggest so. You can do your own repository with this theme and I'll add a link in the README to that.

**Comment by CharlieS1103** [comment]
@morpheusthewhite Wouldn't it be easier to just fork the spicetify-themes repository, and just drag the Dreary folder in? Then i can just try and keep my commits organized.

**Comment by morpheusthewhite** [comment]
If you push only on the Dready folder then it's not really useful to keep other themes since everyone will just use that repository for your theme.

**Comment by CharlieS1103** [comment]
@morpheusthewhite So should ai close my other pull request and create a repository just for dreary? And what should I do if I plan on making more themes?

**Comment by morpheusthewhite** [comment]
> @morpheusthewhite So should ai close my other pull request and create a repository just for dreary? 

I would say so.

> And what should I do if I plan on making more themes?

Open a PR here.

**Pull request closed without merging**
