### PR TITLE
Adding Dreary theme

### PR DESCRIPTION
**Pull request by CharlieS1103**
All changes up to this point, will be sure to keep commit history organized.

### CODE REVIEW

**Comment by CharlieS1103** [comment]
@morpheusthewhite So do I close this pull request?

**Comment by morpheusthewhite** [comment]
Yes

**Comment by CharlieS1103** [comment]
Alright, by the way if you ever get annoyed by my pull requests and comments feel free to tell me, Im not the most talented hint taker.

**Comment by morpheusthewhite** [comment]
> Alright, by the way if you ever get annoyed by my pull requests and comments feel free to tell me, Im not the most talented hint taker.

No, it's great that you want to contribute and open all this PR. If I get to reply to you quite late sometimes it is because your PRs require reviewing a lot of content, so I need to find some time to sit and explain what I like and what I don't like, as I've also done for this theme in the other PR.

**Pull request closed without merging**
