### PR TITLE
Re-add [horizon] theme to Dribbblish

### PR DESCRIPTION
**Pull request by Delta-official**

### CODE REVIEW

**Review by morpheusthewhite — CHANGES_REQUESTED** [review]
Add a screenshot to the README and to THEMES.md

**Comment by Delta-official** [comment]
Okay, got it, will add a screen

**Comment by Delta-official** [comment]
I am currently unable to add screenshots due to #403

**Comment by Delta-official** [comment]
Fixed the problem, will now add screenshots

**Comment by Delta-official** [comment]
@morpheusthewhite I have added screenshots: #405

**Comment by morpheusthewhite** [comment]
Why did you open two different Pull requests? Please add the screenshots to this Pull Request (I will close the other)

**Comment by Delta-official** [comment]
uh, because that's how you do it?
as far as i know you are not able to push the pull request

**Comment by morpheusthewhite** [comment]
You are, you can just push commits on the branch of this pull request and it will work

**Comment by Delta-official** [comment]
@morpheusthewhite done

**Comment by khanhas** [comment]
Thanks for your contribution. But sorry, it doesn't look good.

**Comment by Delta-official** [comment]
:(

**Pull request closed without merging**
