### PR TITLE
Sleek Updates

### PR DESCRIPTION
**Pull request by CharlieS1103**
- Made buttons more responsive (Play/pause button as well as playlist select buttons.) 
- Revised earthy and lover themes according to Morpheus's suggestions. Updated images. A
- Added border to playlist select to break up the themes a bit
- Made play/pause button bigger 
- Made Player text color be assigned to spice-misc to allow more customization.
- Boxed the playlist li's to give them more distinct appearance, and added small hover animation.
- Changed Coloring to make everything more readable
- Changed Psycho and Bib's Button Coloring to allow the animation to be seen

Theme Colors are a **WIP**
_If you have any ideas please dm me at the discord below, or suggest them here._
If anyone wants to contact me about the themes here to give suggestions in a more timely and easier way, here's my discord. 
_charlieS#1351_

### CODE REVIEW

**Comment by CharlieS1103** [comment]
I'm not quite sure why the validate theme name check failed, any thoughts or does it not matter?

**Comment by CharlieS1103** [comment]
I'm not sure about the border around the playlist selection as well as the gradient, I can remove it if you'd like.

**Comment by morpheusthewhite** [comment]
Sorry, I preferred the previous Sleek look. 

Also, I personally don't like the colour schemes (there are still some elements that are not readable). 

Lastly, do not create a pull request with different changes, or it will not be possible to merge it if there is something that is not suitable for the repository. For example in this case you should have opened a PR for the colour schemes and another for the UI changes. 

But thanks for contributing.

**Comment by morpheusthewhite** [comment]
In general, create pull requests for changes as much atomic as possible. It makes it easier to review them.

**Comment by CharlieS1103** [comment]
@morpheusthewhite Alright, will try to do so in the future

**Pull request closed without merging**
