### PR TITLE
Adds Dribbblish/Nord-Darker

### PR DESCRIPTION
**Pull request by katawajojo**
Adds a new color scheme for Dribblish; Nord Darker. This color scheme more closely follows the design of Nord's template for dark programs.
nord-darker

### CODE REVIEW

**Comment by khanhas** [comment]
Thank you for your contribution.
But slightly different version of existing color schemes is not really necessary.

**Comment by katawajojo** [comment]
Okay, what would you recommend then, since the current Dribbblish/Nord-Dark doesn't follow the design language of Nord for dark applications?

**Comment by khanhas** [comment]
My point is Spicetify is already designed to be easily to customise, it would not be hard for power users like you to apply any "design language". Dribbblish itself is a base, my initial intention is giving a base and user can change to or build upon whatever they feel right. But now it's README page is clustered with dozen of color schemes, some of them are just slightly different. So I hope you understand why I'm very picky on accepting new color scheme.

**Comment by katawajojo** [comment]
Oh no, I definitely understand the reasoning. I wasn't sure if you'd rather I just update the original Nord-Dark, or just leave it as is and keep the change to myself lol

**Pull request closed without merging**
