### PR TITLE
feat(Turntable): add Turntable theme

### PR DESCRIPTION
**Pull request by grasonchan**
Hi.

Here is my theme for spicetify v1. It's based on Spotify original theme.

The new version for spicetify v2 is almost completed, i will open another PR later.

## Important Changes

- now playing bar
  - cover image and "expand & collapse" button
  - position of playback bar
- global like button
- blur modal backdrop
- redesign and response the Full App Dispaly

## Preview

turntable

full_app_display

### CODE REVIEW

**Review by morpheusthewhite — CHANGES_REQUESTED** [review]
Can you change the name of the theme? I don't like the fact that there's Spotify in it

**Comment by grasonchan** [comment]
Yep, i have this concern, so i always put it in my repository. Because naming is very difficult to me.

I renamed it and  there isn't better name. I may remame it again in the future.

Then, i have a request. Can i put two screenshots on the Wiki and THEMES.md of the v2 branch?

Because the Full App Display is an important part of my theme. In the new version, i control the rotation of the turntable by playing state.

**Comment by morpheusthewhite** [comment]
I'd prefer putting just one, maybe it could be the full app display screenshot. People interested could still go check it out in its folder

**Review by morpheusthewhite — APPROVED** [review]

**Comment by grasonchan** [comment]
Okay, i have seen it in the "Themes preview".

Thanks.

**Pull request merged**
